import React, { useMemo, useState } from 'react';
import { Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native';
import { getGetProductsQueryKey, useAdjustInventory, useGetAuthSession, useGetProducts } from '@workspace/api-client-react';
import type { Product } from '@workspace/api-client-react';
import { Feather } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { OfflineBanner } from '@/components/OfflineBanner';
import { OutboxPanel } from '@/components/OutboxPanel';
import { ErrorState, ScreenHeader, ScreenSkeleton, SignedOutState, getTopInset, formatMoney } from '@/components/BusinessUI';
import { useColors } from '@/hooks/useColors';

export default function InventoryScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const topInset = getTopInset(insets.top);
  const session = useGetAuthSession(); const [search, setSearch] = useState('');
  const products = useGetProducts(search.trim() ? { search: search.trim() } : undefined, { query: { queryKey: getGetProductsQueryKey(search.trim() ? { search: search.trim() } : undefined), enabled: !!session.data?.authenticated } });
  const adjust = useAdjustInventory(); const [adjusting, setAdjusting] = useState<number | null>(null); const [quantity, setQuantity] = useState('1'); const [message, setMessage] = useState('');
  const canAdjust = session.data?.authenticated && ['admin', 'manager'].includes(session.data.employee.role);
  const list = useMemo(() => products.data ?? [], [products.data]);
  if (session.isLoading || products.isLoading) return <ScreenSkeleton colors={colors} topInset={topInset} />;
  if (!session.data?.authenticated) return <SignedOutState colors={colors} topInset={topInset} />;
  if (products.isError) return <ErrorState title="Inventory unavailable" message="The catalog could not be loaded." onRetry={() => void products.refetch()} colors={colors} topInset={topInset} />;
  const submitAdjust = (product: Product, delta: number) => {
    const value = Number(quantity); if (!Number.isFinite(value) || value <= 0) { setMessage('Enter a quantity greater than zero.'); return; }
    setMessage('');
    adjust.mutate({ data: { productId: product.id, quantity: delta * value, reason: delta > 0 ? 'mobile_restock' : 'mobile_correction', idempotencyKey: `${Date.now()}-${product.id}` } }, { onSuccess: () => { setMessage(`${product.name} stock updated.`); setAdjusting(null); setQuantity('1'); void products.refetch(); }, onError: () => setMessage('Stock could not be updated. Managers can retry when connected.') });
  };
  return <View style={[styles.screen, { backgroundColor: colors.background }]}><View style={[styles.scroll, { paddingTop: topInset + 20, paddingBottom: insets.bottom + 110 }]}><ScreenHeader eyebrow="MOBILINQ / INVENTORY" title="Know what is on hand." subtitle="Fast stock checks for the floor, with manager controls when needed." icon="package" colors={colors} /><OfflineBanner /><OutboxPanel /><View style={[styles.search, { borderColor: colors.border, backgroundColor: colors.card }]}><Feather name="search" size={16} color={colors.mutedForeground} /><TextInput testID="inventory-search" value={search} onChangeText={setSearch} placeholder="Search product or SKU" placeholderTextColor={colors.mutedForeground} style={[styles.searchInput, { color: colors.foreground }]} /></View>{!!message && <Text style={[styles.message, { color: colors.primary }]}>{message}</Text>}<Text style={[styles.caption, { color: colors.mutedForeground }]}>{list.length} product{list.length === 1 ? '' : 's'} · stock counts reflect the selected store</Text>{list.map((product) => { const low = product.stock <= 0; return <View key={product.id} style={[styles.card, { backgroundColor: colors.card, borderColor: low ? colors.destructive : colors.border }]}><View style={[styles.icon, { backgroundColor: colors.accent }]}><Feather name={low ? 'alert-triangle' : 'package'} size={16} color={low ? colors.destructive : colors.primary} /></View><View style={styles.copy}><Text style={[styles.name, { color: colors.foreground }]} numberOfLines={1}>{product.name}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{product.sku} · {formatMoney(product.price)}</Text></View><View style={styles.stock}><Text style={[styles.stockValue, { color: low ? colors.destructive : colors.foreground }]}>{product.stock}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>ON HAND</Text></View>{canAdjust ? <Pressable testID={`adjust-${product.id}`} accessibilityRole="button" onPress={() => setAdjusting(adjusting === product.id ? null : product.id)} style={styles.iconButton}><Feather name="edit-3" size={16} color={colors.primary} /></Pressable> : null}{adjusting === product.id ? <View style={[styles.adjust, { borderTopColor: colors.border }]}><TextInput value={quantity} onChangeText={setQuantity} keyboardType="decimal-pad" style={[styles.qty, { borderColor: colors.border, color: colors.foreground }]} /><Pressable onPress={() => submitAdjust(product, -1)} style={[styles.smallButton, { backgroundColor: colors.accent }]}><Text style={[styles.smallText, { color: colors.destructive }]}>- REMOVE</Text></Pressable><Pressable onPress={() => submitAdjust(product, 1)} style={[styles.smallButton, { backgroundColor: colors.secondary }]}><Text style={[styles.smallText, { color: colors.primary }]}>+ ADD</Text></Pressable></View> : null}</View>; })}</View></View>;
}

const styles = StyleSheet.create({ screen: { flex: 1 }, scroll: { flexGrow: 1, paddingHorizontal: 18 }, search: { minHeight: 46, borderWidth: 1, borderRadius: 11, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 }, searchInput: { flex: 1, fontSize: 14, paddingVertical: 10 }, message: { fontSize: 12, marginBottom: 9 }, caption: { fontSize: 11, marginBottom: 9 }, card: { minHeight: 72, borderWidth: 1, borderRadius: 13, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 9, flexWrap: 'wrap' }, icon: { width: 36, height: 36, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1, minWidth: 120 }, name: { fontSize: 13, fontWeight: '700' }, meta: { fontSize: 10, marginTop: 3 }, stock: { alignItems: 'flex-end' }, stockValue: { fontSize: 20, fontWeight: '700' }, iconButton: { padding: 8 }, adjust: { width: '100%', borderTopWidth: 1, paddingTop: 10, flexDirection: 'row', gap: 8, alignItems: 'center' }, qty: { width: 62, height: 38, borderWidth: 1, borderRadius: 8, paddingHorizontal: 9, textAlign: 'center' }, smallButton: { minHeight: 38, borderRadius: 8, paddingHorizontal: 10, alignItems: 'center', justifyContent: 'center' }, smallText: { fontSize: 9, fontWeight: '700', letterSpacing: 0.4 } });