// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/billpro/DarkTerminal.tsx": () => import("../components/mockups/billpro/DarkTerminal.tsx"),
  "./components/mockups/billpro/MinimalTypographic.tsx": () => import("../components/mockups/billpro/MinimalTypographic.tsx"),
  "./components/mockups/billpro/WarmBoutique.tsx": () => import("../components/mockups/billpro/WarmBoutique.tsx")
};
